/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_my_ndk_ExampleAndroidJni */

#ifndef _Included_com_my_ndk_ExampleAndroidJni
#define _Included_com_my_ndk_ExampleAndroidJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_my_ndk_ExampleAndroidJni
 * Method:    nativeGetAudioTracks
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_my_ndk_ExampleAndroidJni_nativeGetAudioTracks
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
