/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_my_ndk_MyJni */

#ifndef _Included_com_my_ndk_MyJni
#define _Included_com_my_ndk_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_my_ndk_MyJni
 * Method:    setGetString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_my_ndk_MyJni_setGetString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_my_ndk_MyJni
 * Method:    myStatic
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_my_ndk_MyJni_myStatic
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
